### ISSUE TITLE
bug-shfa

### ISSUE THREAD

**Issue by IZBH** [transmatrix-github/HFA_release#1]
![image](https://user-images.githubusercontent.com/61223505/79003658-9b06c380-7b85-11ea-8545-bb4f3505685f.png)

There is no problem with demo.m. When I run the demo_shfa.m,There was an error at line 42 in the demo_shfa.m file.
[target_training_index, target_test_index] = return_object_target_index_diff_number(tar_num, target_training_index, target_test_index)

**Comment by colorfuloranges** [comment]
> ![image](https://user-images.githubusercontent.com/61223505/79003658-9b06c380-7b85-11ea-8545-bb4f3505685f.png)
> 
> There is no problem with demo.m. When I run the demo_shfa.m,There was an error at line 42 in the demo_shfa.m file.
> [target_training_index, target_test_index] = return_object_target_index_diff_number(tar_num, target_training_index, target_test_index)

hello,I meet the same error. Did you resolve it?

**Comment by helloworld1973** [comment]
same error

**Comment by yangguangan** [comment]
> same error

Me too, did you resolve it?  Maybe we can discuss it.

**Comment by wenli-vision** [comment]
Finally, I found the code. Now the missed file has been uploaded. You should be able to run the demo_shfa now.
